export const playfulPalettes = {
  candy: {
    name: 'Candy',
    background: '#fff7fb',
    foreground: '#18181b',
    primary: '#ff4ecd',
    secondary: '#7c3aed',
    accent: '#00d9ff',
    success: '#3ee98f',
    warning: '#ffd166',
    danger: '#ff5a5f',
  },
  sunny: {
    name: 'Sunny',
    background: '#fff8dc',
    foreground: '#1f1b14',
    primary: '#ffb703',
    secondary: '#fb8500',
    accent: '#219ebc',
    success: '#06d6a0',
    warning: '#ffd166',
    danger: '#ef476f',
  },
  mint: {
    name: 'Mint',
    background: '#effdf7',
    foreground: '#10231c',
    primary: '#2dd4bf',
    secondary: '#14b8a6',
    accent: '#a3e635',
    success: '#22c55e',
    warning: '#facc15',
    danger: '#fb7185',
  },
  grape: {
    name: 'Grape',
    background: '#faf5ff',
    foreground: '#1e102f',
    primary: '#a855f7',
    secondary: '#ec4899',
    accent: '#38bdf8',
    success: '#4ade80',
    warning: '#fbbf24',
    danger: '#f43f5e',
  },
} as const
