import type { ComponentFamilyDoc } from './types'

const buttonProps = [
  { name: 'size', type: 'sm | md | lg | xl', defaultValue: 'md', description: 'Control height, padding, and text size.' },
  { name: 'tone', type: 'default | success | error | warning | info | neutral', defaultValue: 'default', description: 'Semantic state color for the same visual variation.' },
  { name: 'motionPreset', type: 'none | pop | squish | wiggle', defaultValue: 'pop', description: 'Interaction animation preset.' },
  { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Disables the button and shows a spinner.' },
  { name: 'leftIcon / rightIcon', type: 'ReactNode', description: 'Optional icons around the label.' },
]

const inputProps = [
  { name: 'inputSize', type: 'sm | md | lg | xl', defaultValue: 'md', description: 'Control height, padding, and text size.' },
  { name: 'tone', type: 'default | success | error | warning | info | neutral', defaultValue: 'default', description: 'Semantic state color for the same visual variation.' },
  { name: 'motionPreset', type: 'none | lift | squish | glow', defaultValue: 'lift', description: 'Focus and hover animation preset.' },
  { name: 'invalid', type: 'boolean', defaultValue: 'false', description: 'Marks the field invalid and applies the error tone.' },
  { name: 'label', type: 'ReactNode', description: 'Optional visible field label.' },
  { name: 'hint / error', type: 'ReactNode', description: 'Optional helper or validation message below the input.' },
  { name: 'placeholder', type: 'string', description: 'Native input placeholder.' },
]

const basicHtmlProps = [
  { name: 'className', type: 'string', description: 'Optional class override.' },
  { name: 'children', type: 'ReactNode', description: 'Visible component content.' },
]

export const componentRegistry: Array<ComponentFamilyDoc> = [
  {
    familySlug: 'buttons',
    familyName: 'Buttons',
    description: 'CTA components with separate named visual variations.',
    packageName: '@playful/components/buttons',
    cliCommand: 'npx playful-ui add buttons',
    aiPrompt: 'Use Playful Components button variations. Prefer named imports like StickerPopButton or BubbleGumButton from the buttons family. Pick tone="success" for positive actions, tone="error" for destructive actions, loading for pending actions, and QuietGhostButton for low-emphasis actions. Keep className overrides scoped with CSS variables.',
    tags: ['button', 'cta', 'motion'],
    props: buttonProps,
    variations: [
      {
        slug: 'sticker-pop',
        name: 'Sticker Pop Button',
        description: 'Chunky sticker CTA with a hard shadow and candy-pink fill.',
        componentName: 'StickerPopButton',
        importPath: '@/components/playful/buttons/sticker-pop',
        tags: ['button', 'sticker', 'cta'],
        status: 'ready',
        tokens: ['--pc-color-pink', '--pc-button-shadow', '--pc-radius-lg'],
        props: buttonProps,
      },
      {
        slug: 'bubble-gum',
        name: 'Bubble Gum Button',
        description: 'Round pill button with glossy inset pressure and squishy motion.',
        componentName: 'BubbleGumButton',
        importPath: '@/components/playful/buttons/bubble-gum',
        tags: ['button', 'bubble', 'pill'],
        status: 'ready',
        tokens: ['--pc-color-blue', '--pc-button-inset-shadow', '--pc-radius-full'],
        props: buttonProps,
      },
      {
        slug: 'neon-gradient',
        name: 'Neon Gradient Button',
        description: 'High-energy gradient action for hero and upgrade flows.',
        componentName: 'NeonGradientButton',
        importPath: '@/components/playful/buttons/neon-gradient',
        tags: ['button', 'gradient', 'hero'],
        status: 'ready',
        tokens: ['--pc-color-pink', '--pc-color-purple', '--pc-color-blue'],
        props: buttonProps,
      },
      {
        slug: 'soft-candy',
        name: 'Soft Candy Button',
        description: 'Lower-emphasis candy button for secondary actions.',
        componentName: 'SoftCandyButton',
        importPath: '@/components/playful/buttons/soft-candy',
        tags: ['button', 'soft', 'secondary'],
        status: 'ready',
        tokens: ['--pc-color-mint', '--pc-surface-soft', '--pc-radius-lg'],
        props: buttonProps,
      },
      {
        slug: 'sketch-outline',
        name: 'Sketch Outline Button',
        description: 'White outline button with a hand-cut sticker attitude.',
        componentName: 'SketchOutlineButton',
        importPath: '@/components/playful/buttons/sketch-outline',
        tags: ['button', 'outline', 'neutral'],
        status: 'ready',
        tokens: ['--pc-border-color', '--pc-shadow-sticker', '--pc-surface'],
        props: buttonProps,
      },
      {
        slug: 'quiet-ghost',
        name: 'Quiet Ghost Button',
        description: 'Minimal action that still inherits playful focus and motion.',
        componentName: 'QuietGhostButton',
        importPath: '@/components/playful/buttons/quiet-ghost',
        tags: ['button', 'ghost', 'minimal'],
        status: 'ready',
        tokens: ['--pc-ink', '--pc-surface-soft', '--pc-radius-md'],
        props: buttonProps,
      },
    ],
  },
  {
    familySlug: 'tooltips',
    familyName: 'Tooltips',
    description: 'Small explainers for props, tokens, and compact UI hints.',
    packageName: '@playful/components/tooltips',
    cliCommand: 'npx playful-ui add tooltips',
    aiPrompt: 'Use PopoverTipTooltip for short hover/focus help. Keep content concise, wrap an existing trigger, and do not use it for critical mobile-only information.',
    tags: ['tooltip', 'overlay', 'help'],
    props: [
      { name: 'content', type: 'ReactNode', description: 'Tooltip body.' },
      { name: 'children', type: 'ReactNode', description: 'Trigger content.' },
      { name: 'className', type: 'string', description: 'Optional wrapper class.' },
    ],
    variations: [
      {
        slug: 'popover-tip',
        name: 'Popover Tip Tooltip',
        description: 'A compact focus and hover tooltip with a sticker-like panel.',
        componentName: 'PopoverTipTooltip',
        importPath: '@/components/playful/tooltips/popover-tip',
        tags: ['tooltip', 'focus', 'hover'],
        status: 'ready',
        tokens: ['--pc-ink', '--pc-surface', '--pc-shadow-sticker'],
        props: [
          { name: 'content', type: 'ReactNode', description: 'Tooltip body.' },
          { name: 'children', type: 'ReactNode', description: 'Trigger content.' },
          { name: 'className', type: 'string', description: 'Optional wrapper class.' },
        ],
      },
    ],
  },
  {
    familySlug: 'badges',
    familyName: 'Badges',
    description: 'Compact tags for statuses, labels, and release notes.',
    packageName: '@playful/components/badges',
    cliCommand: 'npx playful-ui add badges',
    aiPrompt: 'Use FeatureStickerBadge for compact labels such as Beta, New, Stable, or status chips. Keep badge text short.',
    tags: ['badge', 'status', 'label'],
    props: [
      { name: 'dot', type: 'boolean', defaultValue: 'true', description: 'Show the leading dot.' },
      ...basicHtmlProps,
    ],
    variations: [
      {
        slug: 'feature-sticker',
        name: 'Feature Sticker Badge',
        description: 'Tiny pill sticker with an optional colored dot.',
        componentName: 'FeatureStickerBadge',
        importPath: '@/components/playful/badges/feature-sticker',
        tags: ['badge', 'sticker', 'status'],
        status: 'ready',
        tokens: ['--pc-color-yellow', '--pc-border-color', '--pc-radius-full'],
        props: [
          { name: 'dot', type: 'boolean', defaultValue: 'true', description: 'Show the leading dot.' },
          { name: 'children', type: 'ReactNode', description: 'Badge label.' },
        ],
      },
    ],
  },
  {
    familySlug: 'cards',
    familyName: 'Cards',
    description: 'Framed surfaces for previews, docs, and feature callouts.',
    packageName: '@playful/components/cards',
    cliCommand: 'npx playful-ui add cards',
    aiPrompt: 'Use FeatureStickerCard as a framed surface. Set interactive only when the whole card behaves like an action or clickable preview.',
    tags: ['card', 'surface', 'preview'],
    props: [
      { name: 'interactive', type: 'boolean', defaultValue: 'false', description: 'Enable subtle hover/tap motion.' },
      ...basicHtmlProps,
    ],
    variations: [
      {
        slug: 'feature-sticker',
        name: 'Feature Sticker Card',
        description: 'A solid bordered card with sticker shadow and hover lift.',
        componentName: 'FeatureStickerCard',
        importPath: '@/components/playful/cards/feature-sticker',
        tags: ['card', 'sticker', 'surface'],
        status: 'ready',
        tokens: ['--pc-surface', '--pc-card-shadow', '--pc-radius-xl'],
        props: [
          { name: 'children', type: 'ReactNode', description: 'Card content.' },
          { name: 'className', type: 'string', description: 'Optional class override.' },
        ],
      },
    ],
  },
  {
    familySlug: 'inputs',
    familyName: 'Inputs',
    description: 'Text fields with named visual variations, semantic tones, and Motion focus states.',
    packageName: '@playful/components/inputs',
    cliCommand: 'npx playful-ui add inputs',
    aiPrompt: 'Use Playful Components input variations. Prefer named imports like CandyFieldInput or BubbleFieldInput from the inputs family. Pick tone="success" for accepted values, tone="error" or invalid for validation errors, and provide label plus hint/error when the field needs context. Keep native input props and use inputSize for sizing.',
    tags: ['input', 'form', 'field', 'motion'],
    props: inputProps,
    variations: [
      {
        slug: 'candy-field',
        name: 'Candy Field Input',
        description: 'Chunky sticker input for search and high-visibility form fields.',
        componentName: 'CandyFieldInput',
        importPath: '@/components/playful/inputs/candy-field',
        tags: ['input', 'form', 'sticker'],
        status: 'ready',
        tokens: ['--pc-surface', '--pc-input-shadow', '--pc-radius-lg'],
        props: inputProps,
      },
      {
        slug: 'bubble-field',
        name: 'Bubble Field Input',
        description: 'Round pill input with bubbly pressure and soft blue surface.',
        componentName: 'BubbleFieldInput',
        importPath: '@/components/playful/inputs/bubble-field',
        tags: ['input', 'bubble', 'pill'],
        status: 'ready',
        tokens: ['--pc-color-blue', '--pc-radius-full', '--pc-input-shadow'],
        props: inputProps,
      },
      {
        slug: 'glow-field',
        name: 'Glow Field Input',
        description: 'Dark gradient-border input for expressive search and command fields.',
        componentName: 'GlowFieldInput',
        importPath: '@/components/playful/inputs/glow-field',
        tags: ['input', 'gradient', 'dark'],
        status: 'ready',
        tokens: ['--pc-color-pink', '--pc-color-purple', '--pc-color-blue'],
        props: inputProps,
      },
      {
        slug: 'sketch-field',
        name: 'Sketch Field Input',
        description: 'Hand-cut outline input with a bold offset shadow.',
        componentName: 'SketchFieldInput',
        importPath: '@/components/playful/inputs/sketch-field',
        tags: ['input', 'outline', 'neutral'],
        status: 'ready',
        tokens: ['--pc-color-background-soft', '--pc-border-color', '--pc-radius-lg'],
        props: inputProps,
      },
    ],
  },
  {
    familySlug: 'switches',
    familyName: 'Switches',
    description: 'Accessible toggle controls with animated thumbs.',
    packageName: '@playful/components/switches',
    cliCommand: 'npx playful-ui add switches',
    aiPrompt: 'Use MintToggleSwitch for boolean settings. Provide aria-label when no visible label exists, and use checked/onChange for controlled state.',
    tags: ['switch', 'toggle', 'form'],
    props: [
      { name: 'checked', type: 'boolean', description: 'Controlled checked state.' },
      { name: 'defaultChecked', type: 'boolean', defaultValue: 'false', description: 'Initial uncontrolled state.' },
      { name: 'onChange', type: '(checked: boolean) => void', description: 'Called when the value changes.' },
    ],
    variations: [
      {
        slug: 'mint-toggle',
        name: 'Mint Toggle Switch',
        description: 'A mint on/off switch with a chunky thumb.',
        componentName: 'MintToggleSwitch',
        importPath: '@/components/playful/switches/mint-toggle',
        tags: ['switch', 'toggle', 'form'],
        status: 'ready',
        tokens: ['--pc-color-mint', '--pc-border-color', '--pc-radius-full'],
        props: [
          { name: 'checked', type: 'boolean', description: 'Controlled checked state.' },
          { name: 'defaultChecked', type: 'boolean', defaultValue: 'false', description: 'Initial uncontrolled state.' },
          { name: 'onChange', type: '(checked: boolean) => void', description: 'Called when the value changes.' },
        ],
      },
    ],
  },
  {
    familySlug: 'checkboxes',
    familyName: 'Checkboxes',
    description: 'Playful checkbox controls that keep native input behavior.',
    packageName: '@playful/components/checkboxes',
    cliCommand: 'npx playful-ui add checkboxes',
    aiPrompt: 'Use StarCheckCheckbox for opt-in form choices. Prefer visible labels; use checked/onChange when controlled.',
    tags: ['checkbox', 'form', 'input'],
    props: [
      { name: 'label', type: 'ReactNode', description: 'Optional visible label.' },
      { name: 'checked', type: 'boolean', description: 'Controlled checked state.' },
      { name: 'onChange', type: '(checked: boolean) => void', description: 'Called when the value changes.' },
    ],
    variations: [
      {
        slug: 'star-check',
        name: 'Star Check Checkbox',
        description: 'A checkbox that fills with a star when selected.',
        componentName: 'StarCheckCheckbox',
        importPath: '@/components/playful/checkboxes/star-check',
        tags: ['checkbox', 'star', 'form'],
        status: 'ready',
        tokens: ['--pc-color-yellow', '--pc-border-color', '--pc-radius-sm'],
        props: [
          { name: 'label', type: 'ReactNode', description: 'Optional visible label.' },
          { name: 'checked', type: 'boolean', description: 'Controlled checked state.' },
          { name: 'onChange', type: '(checked: boolean) => void', description: 'Called when the value changes.' },
        ],
      },
    ],
  },
  {
    familySlug: 'tabs',
    familyName: 'Tabs',
    description: 'Tabbed panels for preview, code, props, and token docs.',
    packageName: '@playful/components/tabs',
    cliCommand: 'npx playful-ui add tabs',
    aiPrompt: 'Use StickerTabs for local view switching such as Preview, Code, Props, and Tokens. Keep tab labels short.',
    tags: ['tabs', 'navigation', 'docs'],
    props: [
      { name: 'items', type: 'Array<{ value; label; content }>', description: 'Tabs and panels.' },
      { name: 'value', type: 'string', description: 'Controlled selected value.' },
      { name: 'onChange', type: '(value: string) => void', description: 'Called when selected tab changes.' },
    ],
    variations: [
      {
        slug: 'sticker-tabs',
        name: 'Sticker Tabs',
        description: 'Pill tabs with an animated sticker indicator.',
        componentName: 'StickerTabs',
        importPath: '@/components/playful/tabs/sticker-tabs',
        tags: ['tabs', 'indicator', 'docs'],
        status: 'ready',
        tokens: ['--pc-color-yellow', '--pc-surface', '--pc-radius-full'],
        props: [
          { name: 'items', type: 'Array<{ value; label; content }>', description: 'Tabs and panels.' },
          { name: 'value', type: 'string', description: 'Controlled selected value.' },
          { name: 'onChange', type: '(value: string) => void', description: 'Called when selected tab changes.' },
        ],
      },
    ],
  },
  {
    familySlug: 'color-pickers',
    familyName: 'Color Pickers',
    description: 'Color selection tools with custom swatches and HEX editing.',
    packageName: '@playful/components/color-pickers',
    cliCommand: 'npx playful-ui add color-pickers',
    aiPrompt: 'Use SwatchPartyColorPicker for simple palette selection. Use value/onChange for controlled forms and pass a custom palette for brand colors.',
    tags: ['color', 'picker', 'form'],
    props: [
      { name: 'value', type: 'string', description: 'Controlled HEX color.' },
      { name: 'palette', type: 'PlayfulColor[]', description: 'Swatch list.' },
      { name: 'onChange', type: '(color: string) => void', description: 'Called when color changes.' },
    ],
    variations: [
      {
        slug: 'swatch-party',
        name: 'Swatch Party Color Picker',
        description: 'A swatch grid color picker with animated preview.',
        componentName: 'SwatchPartyColorPicker',
        importPath: '@/components/playful/color-pickers/swatch-party',
        tags: ['color', 'swatch', 'picker'],
        status: 'ready',
        tokens: ['--pc-color-pink', '--pc-surface', '--pc-radius-lg'],
        props: [
          { name: 'value', type: 'string', description: 'Controlled HEX color.' },
          { name: 'palette', type: 'PlayfulColor[]', description: 'Swatch list.' },
          { name: 'onChange', type: '(color: string) => void', description: 'Called when color changes.' },
        ],
      },
    ],
  },
  {
    familySlug: 'toasts',
    familyName: 'Toasts',
    description: 'Notification surfaces for app feedback.',
    packageName: '@playful/components/toasts',
    cliCommand: 'npx playful-ui add toasts',
    aiPrompt: 'Use PopToast for short feedback. Choose success, info, warning, or danger tone and keep descriptions one sentence.',
    tags: ['toast', 'notification', 'feedback'],
    props: [
      { name: 'tone', type: 'success | info | warning | danger', defaultValue: 'success', description: 'Toast tone.' },
      { name: 'title', type: 'ReactNode', description: 'Toast heading.' },
      { name: 'description', type: 'ReactNode', description: 'Optional supporting copy.' },
    ],
    variations: [
      {
        slug: 'pop-toast',
        name: 'Pop Toast',
        description: 'A compact notification with tone-specific iconography.',
        componentName: 'PopToast',
        importPath: '@/components/playful/toasts/pop-toast',
        tags: ['toast', 'feedback', 'motion'],
        status: 'ready',
        tokens: ['--pc-surface', '--pc-card-shadow', '--pc-radius-lg'],
        props: [
          { name: 'tone', type: 'success | info | warning | danger', defaultValue: 'success', description: 'Toast tone.' },
          { name: 'title', type: 'ReactNode', description: 'Toast heading.' },
          { name: 'description', type: 'ReactNode', description: 'Optional supporting copy.' },
        ],
      },
    ],
  },
]

export function getComponentFamily(familySlug: string) {
  return componentRegistry.find((family) => family.familySlug === familySlug)
}

export function getComponentVariation(familySlug: string, variationSlug: string) {
  return getComponentFamily(familySlug)?.variations.find(
    (variation) => variation.slug === variationSlug,
  )
}
