import type { ComponentFamilyDoc } from './types'

const buttonProps = [
  { name: 'size', type: 'sm | md | lg | xl', defaultValue: 'md', description: 'Control height, padding, and text size.' },
  { name: 'tone', type: 'default | success | error | warning | info | neutral', defaultValue: 'default', description: 'Semantic state color for the same visual variation.' },
  { name: 'motionPreset', type: 'none | pop | squish | wiggle', defaultValue: 'pop', description: 'Interaction animation preset.' },
  { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Disables the button and shows a spinner.' },
  { name: 'icon', type: 'ReactNode', description: 'Optional icon slot from any icon library.' },
  { name: 'iconPosition', type: 'left | right', defaultValue: 'left', description: 'Places the icon before or after the label.' },
  { name: 'leftIcon / rightIcon', type: 'ReactNode', description: 'Explicit icon slots around the label.' },
]

const inputProps = [
  { name: 'inputSize', type: 'sm | md | lg | xl', defaultValue: 'md', description: 'Control height, padding, and text size.' },
  { name: 'tone', type: 'default | success | error | warning | info | neutral', defaultValue: 'default', description: 'Semantic state color for the same visual variation.' },
  { name: 'motionPreset', type: 'none | lift | squish', defaultValue: 'lift', description: 'Focus and hover animation preset.' },
  { name: 'invalid', type: 'boolean', defaultValue: 'false', description: 'Marks the field invalid and applies the error tone.' },
  { name: 'icon', type: 'ReactNode', description: 'Optional icon slot from any icon library.' },
  { name: 'iconPosition', type: 'left | right', defaultValue: 'left', description: 'Places the icon inside the field.' },
  { name: 'leftIcon / rightIcon', type: 'ReactNode', description: 'Explicit icon slots inside the field.' },
  { name: 'label', type: 'ReactNode', description: 'Optional visible field label.' },
  { name: 'hint / error', type: 'ReactNode', description: 'Optional helper or validation message below the input.' },
  { name: 'placeholder', type: 'string', description: 'Native input placeholder.' },
]

const basicHtmlProps = [
  { name: 'className', type: 'string', description: 'Optional class override.' },
  { name: 'children', type: 'ReactNode', description: 'Visible component content.' },
]

export const componentRegistry: Array<ComponentFamilyDoc> = [
  {
    familySlug: 'buttons',
    familyName: 'Buttons',
    description: 'CTA components built on the shared sticker, bubble, and sketch visual vocabulary.',
    packageName: '@playful/components/buttons',
    cliCommand: 'npx playful-cn add buttons',
    aiPrompt: 'Use Playful Components core button variations: StickerPopButton, BubbleGumButton, and SketchOutlineButton. Pick tone="success" for positive actions, tone="error" for destructive actions, loading for pending actions, and QuietGhostButton for low-emphasis button-only actions. Keep className overrides scoped with CSS variables.',
    tags: ['button', 'cta', 'motion'],
    props: buttonProps,
    variations: [
      {
        slug: 'sticker',
        name: 'Sticker Pop Button',
        description: 'Chunky sticker CTA with a hard shadow and candy-pink fill.',
        componentName: 'StickerPopButton',
        importPath: '@/components/playful/buttons/sticker-pop',
        coreVariant: 'sticker',
        category: 'core',
        tags: ['button', 'sticker', 'core', 'cta'],
        status: 'ready',
        tokens: ['--pc-color-pink', '--pc-button-shadow', '--pc-radius-lg'],
        props: buttonProps,
      },
      {
        slug: 'bubble',
        name: 'Bubble Gum Button',
        description: 'Round pill button with glossy inset pressure and squishy motion.',
        componentName: 'BubbleGumButton',
        importPath: '@/components/playful/buttons/bubble-gum',
        coreVariant: 'bubble',
        category: 'core',
        tags: ['button', 'bubble', 'core', 'pill'],
        status: 'ready',
        tokens: ['--pc-color-blue', '--pc-button-inset-shadow', '--pc-radius-full'],
        props: buttonProps,
      },
      {
        slug: 'sketch',
        name: 'Sketch Outline Button',
        description: 'White outline button with a hand-cut sticker attitude.',
        componentName: 'SketchOutlineButton',
        importPath: '@/components/playful/buttons/sketch-outline',
        coreVariant: 'sketch',
        category: 'core',
        tags: ['button', 'sketch', 'core', 'outline'],
        status: 'ready',
        tokens: ['--pc-border-color', '--pc-shadow-sticker', '--pc-surface'],
        props: buttonProps,
      },
      {
        slug: 'soft-candy',
        name: 'Soft Candy Button',
        description: 'Button-only extra for lower-emphasis candy actions.',
        componentName: 'SoftCandyButton',
        importPath: '@/components/playful/buttons/soft-candy',
        category: 'extra',
        tags: ['button', 'extra', 'soft', 'secondary'],
        status: 'ready',
        tokens: ['--pc-color-mint', '--pc-surface-soft', '--pc-radius-lg'],
        props: buttonProps,
      },
      {
        slug: 'quiet-ghost',
        name: 'Quiet Ghost Button',
        description: 'Button-only extra for minimal actions that still inherit playful focus and motion.',
        componentName: 'QuietGhostButton',
        importPath: '@/components/playful/buttons/quiet-ghost',
        category: 'extra',
        tags: ['button', 'extra', 'ghost', 'minimal'],
        status: 'ready',
        tokens: ['--pc-ink', '--pc-surface-soft', '--pc-radius-md'],
        props: buttonProps,
      },
    ],
  },
  {
    familySlug: 'tooltips',
    familyName: 'Tooltips',
    description: 'Small explainers for props, tokens, and compact UI hints.',
    packageName: '@playful/components/tooltips',
    cliCommand: 'npx playful-cn add tooltips',
    aiPrompt: 'Use PopoverTipTooltip for short hover/focus help. Keep content concise, wrap an existing trigger, and do not use it for critical mobile-only information.',
    tags: ['tooltip', 'overlay', 'help'],
    props: [
      { name: 'content', type: 'ReactNode', description: 'Tooltip body.' },
      { name: 'children', type: 'ReactNode', description: 'Trigger content.' },
      { name: 'className', type: 'string', description: 'Optional wrapper class.' },
    ],
    variations: [
      {
        slug: 'popover-tip',
        name: 'Popover Tip Tooltip',
        description: 'A compact focus and hover tooltip with a sticker-like panel.',
        componentName: 'PopoverTipTooltip',
        importPath: '@/components/playful/tooltips/popover-tip',
        tags: ['tooltip', 'focus', 'hover'],
        status: 'ready',
        tokens: ['--pc-ink', '--pc-surface', '--pc-shadow-sticker'],
        props: [
          { name: 'content', type: 'ReactNode', description: 'Tooltip body.' },
          { name: 'children', type: 'ReactNode', description: 'Trigger content.' },
          { name: 'className', type: 'string', description: 'Optional wrapper class.' },
        ],
      },
    ],
  },
  {
    familySlug: 'badges',
    familyName: 'Badges',
    description: 'Compact tags for statuses, labels, and release notes.',
    packageName: '@playful/components/badges',
    cliCommand: 'npx playful-cn add badges',
    aiPrompt: 'Use FeatureStickerBadge for compact labels such as Beta, New, Stable, or status chips. Keep badge text short.',
    tags: ['badge', 'status', 'label'],
    props: [
      { name: 'dot', type: 'boolean', defaultValue: 'true', description: 'Show the leading dot.' },
      ...basicHtmlProps,
    ],
    variations: [
      {
        slug: 'feature-sticker',
        name: 'Feature Sticker Badge',
        description: 'Tiny pill sticker with an optional colored dot.',
        componentName: 'FeatureStickerBadge',
        importPath: '@/components/playful/badges/feature-sticker',
        tags: ['badge', 'sticker', 'status'],
        status: 'ready',
        tokens: ['--pc-color-yellow', '--pc-border-color', '--pc-radius-full'],
        props: [
          { name: 'dot', type: 'boolean', defaultValue: 'true', description: 'Show the leading dot.' },
          { name: 'children', type: 'ReactNode', description: 'Badge label.' },
        ],
      },
    ],
  },
  {
    familySlug: 'cards',
    familyName: 'Cards',
    description: 'Framed surfaces for previews, docs, and feature callouts.',
    packageName: '@playful/components/cards',
    cliCommand: 'npx playful-cn add cards',
    aiPrompt: 'Use FeatureStickerCard as a framed surface. Set interactive only when the whole card behaves like an action or clickable preview.',
    tags: ['card', 'surface', 'preview'],
    props: [
      { name: 'interactive', type: 'boolean', defaultValue: 'false', description: 'Enable subtle hover/tap motion.' },
      ...basicHtmlProps,
    ],
    variations: [
      {
        slug: 'feature-sticker',
        name: 'Feature Sticker Card',
        description: 'A solid bordered card with sticker shadow and hover lift.',
        componentName: 'FeatureStickerCard',
        importPath: '@/components/playful/cards/feature-sticker',
        tags: ['card', 'sticker', 'surface'],
        status: 'ready',
        tokens: ['--pc-surface', '--pc-card-shadow', '--pc-radius-xl'],
        props: [
          { name: 'children', type: 'ReactNode', description: 'Card content.' },
          { name: 'className', type: 'string', description: 'Optional class override.' },
        ],
      },
    ],
  },
  {
    familySlug: 'inputs',
    familyName: 'Inputs',
    description: 'Text fields built on the shared sticker, bubble, and sketch visual vocabulary.',
    packageName: '@playful/components/inputs',
    cliCommand: 'npx playful-cn add inputs',
    aiPrompt: 'Use Playful Components core input variations: StickerFieldInput, BubbleFieldInput, and SketchFieldInput. CandyFieldInput remains a backward-compatible alias for StickerFieldInput. Pick tone="success" for accepted values, tone="error" or invalid for validation errors, and provide label plus hint/error when the field needs context. Keep native input props and use inputSize for sizing.',
    tags: ['input', 'form', 'field', 'motion'],
    props: inputProps,
    variations: [
      {
        slug: 'sticker',
        name: 'Sticker Field Input',
        description: 'Chunky sticker input for search and high-visibility form fields.',
        componentName: 'StickerFieldInput',
        importPath: '@/components/playful/inputs/sticker-field',
        coreVariant: 'sticker',
        category: 'core',
        tags: ['input', 'form', 'sticker', 'core'],
        status: 'ready',
        tokens: ['--pc-surface', '--pc-input-shadow', '--pc-radius-lg'],
        props: inputProps,
      },
      {
        slug: 'bubble',
        name: 'Bubble Field Input',
        description: 'Round pill input with bubbly pressure and soft blue surface.',
        componentName: 'BubbleFieldInput',
        importPath: '@/components/playful/inputs/bubble-field',
        coreVariant: 'bubble',
        category: 'core',
        tags: ['input', 'bubble', 'core', 'pill'],
        status: 'ready',
        tokens: ['--pc-color-blue', '--pc-radius-full', '--pc-input-shadow'],
        props: inputProps,
      },
      {
        slug: 'sketch',
        name: 'Sketch Field Input',
        description: 'Hand-cut outline input with a bold offset shadow.',
        componentName: 'SketchFieldInput',
        importPath: '@/components/playful/inputs/sketch-field',
        coreVariant: 'sketch',
        category: 'core',
        tags: ['input', 'sketch', 'core', 'outline'],
        status: 'ready',
        tokens: ['--pc-color-background-soft', '--pc-border-color', '--pc-radius-lg'],
        props: inputProps,
      },
    ],
  },
  {
    familySlug: 'textareas',
    familyName: 'Textareas',
    description: 'Expandable text fields with character limits, validation messaging, and three playful skins.',
    packageName: '@playful/components/textareas',
    cliCommand: 'npx playful-cn add textareas',
    aiPrompt: 'Use StickerTextarea, BubbleTextarea, or SketchTextarea for multi-line text. Set maxLength when the content needs a hard limit; the field shows a live character counter.',
    tags: ['textarea', 'form', 'input'],
    props: [{ name: 'maxLength', type: 'number', description: 'Native character limit with live counter.' }, { name: 'label / hint / error', type: 'ReactNode', description: 'Field context and validation copy.' }, { name: 'invalid / loading', type: 'boolean', description: 'Validation and pending states.' }],
    variations: [...['sticker', 'bubble', 'sketch'].map((slug) => ({ slug, name: `${slug[0].toUpperCase()}${slug.slice(1)} Textarea`, description: `Multi-line ${slug} text field.`, componentName: `${slug[0].toUpperCase()}${slug.slice(1)}Textarea`, importPath: `@/components/playful/inputs/${slug}-textarea`, coreVariant: slug as 'sticker' | 'bubble' | 'sketch', category: 'core' as const, tags: ['textarea', slug, 'form'], status: 'ready' as const, tokens: ['--pc-control-accent', '--pc-input-shadow', '--pc-radius-lg'], props: [{ name: 'maxLength', type: 'number', description: 'Character limit and counter.' }, { name: 'label / hint / error', type: 'ReactNode', description: 'Field context.' }] }))],
  },
  {
    familySlug: 'input-groups',
    familyName: 'Input Groups',
    description: 'Composable input rows with leading and trailing addons.',
    packageName: '@playful/components/input-groups',
    cliCommand: 'npx playful-cn add input-groups',
    aiPrompt: 'Use StickerInputGroup, BubbleInputGroup, or SketchInputGroup to compose an input with a prefix, suffix, icon, button, or unit label.',
    tags: ['input-group', 'form', 'composition'],
    props: [{ name: 'start / end', type: 'ReactNode', description: 'Leading and trailing addon slots.' }, { name: 'children', type: 'ReactNode', description: 'Input or compatible control.' }],
    variations: [...['sticker', 'bubble', 'sketch'].map((slug) => ({ slug, name: `${slug[0].toUpperCase()}${slug.slice(1)} Input Group`, description: `Composable ${slug} input row.`, componentName: `${slug[0].toUpperCase()}${slug.slice(1)}InputGroup`, importPath: `@/components/playful/inputs/${slug}-input-group`, coreVariant: slug as 'sticker' | 'bubble' | 'sketch', category: 'core' as const, tags: ['input-group', slug, 'form'], status: 'ready' as const, tokens: ['--pc-control-accent', '--pc-border-color', '--pc-radius-lg'], props: [{ name: 'start / end', type: 'ReactNode', description: 'Addon slots.' }, { name: 'children', type: 'ReactNode', description: 'Input content.' }] }))],
  },
  {
    familySlug: 'input-otp',
    familyName: 'Input OTP',
    description: 'One-time password fields with segmented slots, filtering, limits, and keyboard-friendly input.',
    packageName: '@playful/components/input-otp',
    cliCommand: 'npx playful-cn add input-otp',
    aiPrompt: 'Use StickerInputOTP, BubbleInputOTP, or SketchInputOTP for verification codes. Set length and pattern, and use value/onChange for controlled forms.',
    tags: ['otp', 'input', 'verification'],
    props: [{ name: 'length', type: 'number', defaultValue: '6', description: 'Number of code slots.' }, { name: 'pattern', type: 'string', defaultValue: '[0-9]', description: 'Allowed character pattern.' }, { name: 'value / onChange', type: 'string / function', description: 'Controlled code state.' }],
    variations: [...['sticker', 'bubble', 'sketch'].map((slug) => ({ slug, name: `${slug[0].toUpperCase()}${slug.slice(1)} Input OTP`, description: `Segmented ${slug} verification input.`, componentName: `${slug[0].toUpperCase()}${slug.slice(1)}InputOTP`, importPath: `@/components/playful/inputs/${slug}-input-otp`, coreVariant: slug as 'sticker' | 'bubble' | 'sketch', category: 'core' as const, tags: ['otp', slug, 'form'], status: 'ready' as const, tokens: ['--pc-control-accent', '--pc-border-color', '--pc-radius-md'], props: [{ name: 'length / pattern', type: 'number / string', description: 'Slot count and allowed characters.' }, { name: 'value / onChange', type: 'string / function', description: 'Controlled code state.' }] }))],
  },
  {
    familySlug: 'labels',
    familyName: 'Labels',
    description: 'Accessible form labels with required and optional markers.',
    packageName: '@playful/components/inputs',
    cliCommand: 'npx playful-cn add inputs',
    aiPrompt: 'Use PlayfulLabel to give every form control a visible accessible label, with required or optional context when useful.',
    tags: ['label', 'form', 'accessibility'],
    props: [{ name: 'required', type: 'boolean', description: 'Marks the field as required.' }, { name: 'optional', type: 'ReactNode', description: 'Optional marker content.' }],
    variations: [{ slug: 'base', name: 'Playful Label', description: 'Accessible label with playful form metadata.', componentName: 'PlayfulLabel', importPath: '@/components/playful/inputs/label', tags: ['label', 'form'], status: 'ready', tokens: ['--pc-color-ink', '--pc-color-red'], props: [{ name: 'required / optional', type: 'boolean / ReactNode', description: 'Form metadata.' }] }],
  },
  {
    familySlug: 'fields',
    familyName: 'Fields',
    description: 'Shared field layout for labels, descriptions, errors, and composed controls.',
    packageName: '@playful/components/inputs',
    cliCommand: 'npx playful-cn add inputs',
    aiPrompt: 'Use PlayfulField to compose a label, control, description, and validation error as one accessible form field.',
    tags: ['field', 'form', 'layout'],
    props: [{ name: 'label / description / error', type: 'ReactNode', description: 'Field context.' }, { name: 'invalid', type: 'boolean', description: 'Error state.' }, { name: 'children', type: 'ReactNode', description: 'The form control.' }],
    variations: [{ slug: 'base', name: 'Playful Field', description: 'Composable form field layout.', componentName: 'PlayfulField', importPath: '@/components/playful/inputs/field', tags: ['field', 'form'], status: 'ready', tokens: ['--pc-color-ink', '--pc-color-red'], props: [{ name: 'label / description / error', type: 'ReactNode', description: 'Field context.' }] }],
  },
  {
    familySlug: 'switches',
    familyName: 'Switches',
    description: 'Accessible on/off controls with a shared motion primitive and four playful skins.',
    packageName: '@playful/components/switches',
    cliCommand: 'npx playful-cn add switches',
    aiPrompt: 'Use StickerSwitch, BubbleSwitch, or SketchSwitch for boolean settings. Provide aria-label when no visible label exists, and use checked/onChange for controlled state.',
    tags: ['switch', 'toggle', 'form'],
    props: [
      { name: 'checked', type: 'boolean', description: 'Controlled checked state.' },
      { name: 'defaultChecked', type: 'boolean', defaultValue: 'false', description: 'Initial uncontrolled state.' },
      { name: 'onChange', type: '(checked: boolean) => void', description: 'Called when the value changes.' },
      { name: 'loading / disabled', type: 'boolean', description: 'Prevents interaction and communicates pending state.' },
      { name: 'icon', type: 'ReactNode', description: 'Optional icon inside the switch thumb.' },
    ],
    variations: [
      ...['sticker', 'bubble', 'sketch'].map((slug) => ({
        slug, name: `${slug[0].toUpperCase()}${slug.slice(1)} Switch`, description: `Accessible ${slug} switch with a playful animated thumb.`, componentName: `${slug[0].toUpperCase()}${slug.slice(1)}Switch`, importPath: `@/components/playful/switches/${slug}-switch`, coreVariant: slug as 'sticker' | 'bubble' | 'sketch', category: 'core' as const, tags: ['switch', slug, 'form'], status: 'ready' as const, tokens: ['--pc-control-accent', '--pc-border-color', '--pc-radius-full'], props: [
          { name: 'checked / defaultChecked', type: 'boolean', description: 'Controlled or initial state.' },
          { name: 'onChange', type: '(checked: boolean) => void', description: 'Called when the value changes.' },
          { name: 'icon / loading / disabled', type: 'ReactNode | boolean', description: 'Optional thumb icon and pending/disabled states.' },
        ],
      })),
    ],
  },
  {
    familySlug: 'checkboxes',
    familyName: 'Checkboxes',
    description: 'Native checkbox semantics with indeterminate, validation, loading, and four playful skins.',
    packageName: '@playful/components/checkboxes',
    cliCommand: 'npx playful-cn add checkboxes',
    aiPrompt: 'Use StickerCheckbox, BubbleCheckbox, or SketchCheckbox for opt-in form choices. Prefer visible labels; use checked/onChange when controlled.',
    tags: ['checkbox', 'form', 'input'],
    props: [
      { name: 'label', type: 'ReactNode', description: 'Optional visible label.' },
      { name: 'checked', type: 'boolean', description: 'Controlled checked state.' },
      { name: 'onChange', type: '(checked: boolean) => void', description: 'Called when the value changes.' },
      { name: 'indeterminate', type: 'boolean', defaultValue: 'false', description: 'Shows a mixed selection state.' },
      { name: 'icon / loading / invalid', type: 'ReactNode | boolean', description: 'Optional icon and form feedback states.' },
    ],
    variations: [
      ...['sticker', 'bubble', 'sketch'].map((slug) => ({
        slug, name: `${slug[0].toUpperCase()}${slug.slice(1)} Checkbox`, description: `Accessible ${slug} checkbox with native input behavior.`, componentName: `${slug[0].toUpperCase()}${slug.slice(1)}Checkbox`, importPath: `@/components/playful/checkboxes/${slug}-checkbox`, coreVariant: slug as 'sticker' | 'bubble' | 'sketch', category: 'core' as const, tags: ['checkbox', slug, 'form'], status: 'ready' as const, tokens: ['--pc-control-accent', '--pc-border-color', '--pc-radius-md'], props: [
          { name: 'label / description', type: 'ReactNode', description: 'Visible option copy.' },
          { name: 'checked / defaultChecked', type: 'boolean', description: 'Controlled or initial state.' },
          { name: 'indeterminate / loading / invalid / icon', type: 'boolean | ReactNode', description: 'Mixed, pending, validation, and icon states.' },
        ],
      })),
    ],
  },
  {
    familySlug: 'radio-groups',
    familyName: 'Radio Groups',
    description: 'Single-choice groups with native radio semantics, roving keyboard navigation, and playful skins.',
    packageName: '@playful/components/radio-groups',
    cliCommand: 'npx playful-cn add radio-groups',
    aiPrompt: 'Use StickerRadioGroup, BubbleRadioGroup, or SketchRadioGroup for one-of-many choices. Provide options with value and label, and use value/onChange for controlled state.',
    tags: ['radio', 'form', 'choice'],
    props: [
      { name: 'options', type: 'PlayfulRadioOption[]', description: 'Radio choices with optional descriptions, icons, and disabled states.' },
      { name: 'value / defaultValue', type: 'string', description: 'Controlled or initial selection.' },
      { name: 'orientation', type: 'horizontal | vertical', defaultValue: 'vertical', description: 'Layout and arrow-key direction.' },
      { name: 'invalid / loading', type: 'boolean', description: 'Form feedback and pending states.' },
    ],
    variations: [...['sticker', 'bubble', 'sketch'].map((slug) => ({
      slug, name: `${slug[0].toUpperCase()}${slug.slice(1)} Radio Group`, description: `Accessible ${slug} single-choice group.`, componentName: `${slug[0].toUpperCase()}${slug.slice(1)}RadioGroup`, importPath: `@/components/playful/radio-groups/${slug}-radio-group`, coreVariant: slug as 'sticker' | 'bubble' | 'sketch', category: 'core' as const, tags: ['radio', slug, 'form'], status: 'ready' as const, tokens: ['--pc-control-accent', '--pc-border-color', '--pc-radius-md'], props: [
        { name: 'options', type: 'PlayfulRadioOption[]', description: 'Radio choices with optional descriptions and icons.' },
        { name: 'value / defaultValue', type: 'string', description: 'Controlled or initial selection.' },
        { name: 'onChange / orientation', type: 'function | string', description: 'Selection callback and layout direction.' },
      ],
    }))],
  },
  {
    familySlug: 'tabs',
    familyName: 'Tabs',
    description: 'Tabbed panels for preview, code, props, and token docs.',
    packageName: '@playful/components/tabs',
    cliCommand: 'npx playful-cn add tabs',
    aiPrompt: 'Use StickerTabs for local view switching such as Preview, Code, Props, and Tokens. Keep tab labels short.',
    tags: ['tabs', 'navigation', 'docs'],
    props: [
      { name: 'items', type: 'Array<{ value; label; content }>', description: 'Tabs and panels.' },
      { name: 'value', type: 'string', description: 'Controlled selected value.' },
      { name: 'onChange', type: '(value: string) => void', description: 'Called when selected tab changes.' },
    ],
    variations: [
      {
        slug: 'sticker-tabs',
        name: 'Sticker Tabs',
        description: 'Pill tabs with an animated sticker indicator.',
        componentName: 'StickerTabs',
        importPath: '@/components/playful/tabs/sticker-tabs',
        tags: ['tabs', 'indicator', 'docs'],
        status: 'ready',
        tokens: ['--pc-color-yellow', '--pc-surface', '--pc-radius-full'],
        props: [
          { name: 'items', type: 'Array<{ value; label; content }>', description: 'Tabs and panels.' },
          { name: 'value', type: 'string', description: 'Controlled selected value.' },
          { name: 'onChange', type: '(value: string) => void', description: 'Called when selected tab changes.' },
        ],
      },
    ],
  },
  {
    familySlug: 'color-pickers',
    familyName: 'Color Pickers',
    description: 'Color selection tools with custom swatches and HEX editing.',
    packageName: '@playful/components/color-pickers',
    cliCommand: 'npx playful-cn add color-pickers',
    aiPrompt: 'Use SwatchPartyColorPicker for simple palette selection. Use value/onChange for controlled forms and pass a custom palette for brand colors.',
    tags: ['color', 'picker', 'form'],
    props: [
      { name: 'value', type: 'string', description: 'Controlled HEX color.' },
      { name: 'palette', type: 'PlayfulColor[]', description: 'Swatch list.' },
      { name: 'onChange', type: '(color: string) => void', description: 'Called when color changes.' },
    ],
    variations: [
      {
        slug: 'swatch-party',
        name: 'Swatch Party Color Picker',
        description: 'A swatch grid color picker with animated preview.',
        componentName: 'SwatchPartyColorPicker',
        importPath: '@/components/playful/color-pickers/swatch-party',
        tags: ['color', 'swatch', 'picker'],
        status: 'ready',
        tokens: ['--pc-color-pink', '--pc-surface', '--pc-radius-lg'],
        props: [
          { name: 'value', type: 'string', description: 'Controlled HEX color.' },
          { name: 'palette', type: 'PlayfulColor[]', description: 'Swatch list.' },
          { name: 'onChange', type: '(color: string) => void', description: 'Called when color changes.' },
        ],
      },
    ],
  },
  {
    familySlug: 'toasts',
    familyName: 'Toasts',
    description: 'Notification surfaces for app feedback.',
    packageName: '@playful/components/toasts',
    cliCommand: 'npx playful-cn add toasts',
    aiPrompt: 'Use PopToast for short feedback. Choose success, info, warning, or danger tone and keep descriptions one sentence.',
    tags: ['toast', 'notification', 'feedback'],
    props: [
      { name: 'tone', type: 'success | info | warning | danger', defaultValue: 'success', description: 'Toast tone.' },
      { name: 'title', type: 'ReactNode', description: 'Toast heading.' },
      { name: 'description', type: 'ReactNode', description: 'Optional supporting copy.' },
    ],
    variations: [
      {
        slug: 'pop-toast',
        name: 'Pop Toast',
        description: 'A compact notification with tone-specific iconography.',
        componentName: 'PopToast',
        importPath: '@/components/playful/toasts/pop-toast',
        tags: ['toast', 'feedback', 'motion'],
        status: 'ready',
        tokens: ['--pc-surface', '--pc-card-shadow', '--pc-radius-lg'],
        props: [
          { name: 'tone', type: 'success | info | warning | danger', defaultValue: 'success', description: 'Toast tone.' },
          { name: 'title', type: 'ReactNode', description: 'Toast heading.' },
          { name: 'description', type: 'ReactNode', description: 'Optional supporting copy.' },
        ],
      },
    ],
  },
]

const collectionFamilies = createCollectionFamilies()
for (const family of collectionFamilies) {
  const existingIndex = componentRegistry.findIndex((entry) => entry.familySlug === family.familySlug)
  if (existingIndex >= 0) componentRegistry.splice(existingIndex, 1)
}
componentRegistry.push(...collectionFamilies)

function createCollectionFamilies(): Array<ComponentFamilyDoc> {
  const skins = ['sticker', 'bubble', 'sketch'] as const
  const definitions = [
    ['cards', 'Cards', 'Framed surfaces with playful hover motion.', 'Card', 'cards', ['children', 'interactive']],
    ['badges', 'Badges', 'Compact labels for status, metadata, and release notes.', 'Badge', 'badges', ['children', 'icon']],
    ['alerts', 'Alerts', 'Accessible feedback panels for important context.', 'Alert', 'alerts', ['title', 'description', 'dismissible']],
    ['empties', 'Empty states', 'Friendly guidance for lists and views without content.', 'Empty', 'empties', ['title', 'description', 'action']],
    ['skeletons', 'Skeletons', 'Reduced-motion friendly loading placeholders.', 'Skeleton', 'skeletons', ['lines']],
    ['spinners', 'Spinners', 'Small loading indicators with a pure SVG default.', 'Spinner', 'spinners', ['label', 'size', 'icon']],
    ['progresses', 'Progress', 'Animated determinate progress indicators.', 'Progress', 'progresses', ['value', 'max', 'label', 'showValue']],
    ['dialogs', 'Dialogs', 'Modal conversations with focus management and escape-to-close.', 'Dialog', 'dialogs', ['trigger', 'title', 'description', 'open']],
    ['alert-dialogs', 'Alert Dialogs', 'Modal confirmations for destructive or consequential actions.', 'AlertDialog', 'alert-dialogs', ['trigger', 'title', 'description', 'open']],
    ['drawers', 'Drawers', 'Side-anchored modal panels for focused workflows.', 'Drawer', 'drawers', ['trigger', 'title', 'side', 'open']],
    ['sheets', 'Sheets', 'Responsive modal surfaces for secondary content.', 'Sheet', 'sheets', ['trigger', 'title', 'side', 'open']],
    ['popovers', 'Popovers', 'Anchored interactive content with keyboard dismissal.', 'Popover', 'popovers', ['trigger', 'title', 'side', 'open']],
    ['hover-cards', 'Hover Cards', 'Preview panels revealed on hover or focus.', 'HoverCard', 'hover-cards', ['trigger', 'title', 'description']],
    ['menus', 'Menus', 'Keyboard-friendly action menus with disabled items.', 'Menu', 'menus', ['trigger', 'items', 'open']],
  ] as const
  return definitions.map(([familySlug, familyName, description, baseName, folder, propNames]) => ({
    familySlug,
    familyName,
    description,
    packageName: `@playful/components/${folder}`,
    cliCommand: `npx playful-cn add ${folder}`,
    aiPrompt: `Use the ${baseName} collection with the matching sticker, bubble, or sketch skin. Keep the semantic API intact and provide custom icons through the icon slot when needed.`,
    tags: [familySlug, 'playful', 'motion'],
    props: propNames.map((name) => ({ name, type: name === 'icon' || name === 'action' ? 'ReactNode' : 'component prop', description: `Configures the ${name} slot or behavior.` })),
    variations: skins.map((skin) => ({
      slug: skin,
      name: `${skin[0].toUpperCase()}${skin.slice(1)} ${familyName}`,
      description: `${skin[0].toUpperCase()}${skin.slice(1)} visual skin for ${familyName.toLowerCase()}.`,
      componentName: `${skin[0].toUpperCase()}${skin.slice(1)}${baseName}`,
      importPath: `@/components/playful/${folder}/${skin}`,
      coreVariant: skin,
      category: 'core' as const,
      tags: [familySlug, skin, 'core'],
      status: 'ready' as const,
      tokens: ['--pc-color-pink', '--pc-border-color', '--pc-duration-normal'],
      props: propNames.map((name) => ({ name, type: name === 'icon' || name === 'action' ? 'ReactNode' : 'component prop', description: `Configures the ${name} slot or behavior.` })),
    })),
  }))
}

export function getComponentFamily(familySlug: string) {
  return componentRegistry.find((family) => family.familySlug === familySlug)
}

export function getComponentVariation(familySlug: string, variationSlug: string) {
  const legacySlugs: Record<string, string> = {
    'sticker-pop': 'sticker',
    'bubble-gum': 'bubble',
    'sketch-outline': 'sketch',
    'candy-field': 'sticker',
    'bubble-field': 'bubble',
    'sketch-field': 'sketch',
  }
  const resolvedSlug = legacySlugs[variationSlug] ?? variationSlug

  return getComponentFamily(familySlug)?.variations.find(
    (variation) => variation.slug === resolvedSlug,
  )
}
