/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsFamilyRouteImport } from './routes/components/$family'
import { Route as ComponentsFamilyVariationRouteImport } from './routes/components/$family.$variation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFamilyRoute = ComponentsFamilyRouteImport.update({
  id: '/components/$family',
  path: '/components/$family',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFamilyVariationRoute =
  ComponentsFamilyVariationRouteImport.update({
    id: '/$variation',
    path: '/$variation',
    getParentRoute: () => ComponentsFamilyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/$family': typeof ComponentsFamilyRouteWithChildren
  '/components/': typeof ComponentsIndexRoute
  '/components/$family/$variation': typeof ComponentsFamilyVariationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/$family': typeof ComponentsFamilyRouteWithChildren
  '/components': typeof ComponentsIndexRoute
  '/components/$family/$variation': typeof ComponentsFamilyVariationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/$family': typeof ComponentsFamilyRouteWithChildren
  '/components/': typeof ComponentsIndexRoute
  '/components/$family/$variation': typeof ComponentsFamilyVariationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/$family'
    | '/components/'
    | '/components/$family/$variation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/$family'
    | '/components'
    | '/components/$family/$variation'
  id:
    | '__root__'
    | '/'
    | '/components/$family'
    | '/components/'
    | '/components/$family/$variation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsFamilyRoute: typeof ComponentsFamilyRouteWithChildren
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$family': {
      id: '/components/$family'
      path: '/components/$family'
      fullPath: '/components/$family'
      preLoaderRoute: typeof ComponentsFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$family/$variation': {
      id: '/components/$family/$variation'
      path: '/$variation'
      fullPath: '/components/$family/$variation'
      preLoaderRoute: typeof ComponentsFamilyVariationRouteImport
      parentRoute: typeof ComponentsFamilyRoute
    }
  }
}

interface ComponentsFamilyRouteChildren {
  ComponentsFamilyVariationRoute: typeof ComponentsFamilyVariationRoute
}

const ComponentsFamilyRouteChildren: ComponentsFamilyRouteChildren = {
  ComponentsFamilyVariationRoute: ComponentsFamilyVariationRoute,
}

const ComponentsFamilyRouteWithChildren =
  ComponentsFamilyRoute._addFileChildren(ComponentsFamilyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsFamilyRoute: ComponentsFamilyRouteWithChildren,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
